name: Automated API tests

on: workflow_dispatch
#    inputs:
#      deployment_target:
#        descritpion: Choose target
#        required: true
#        default:
#        type: choice
#        options:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -s -v --reruns 5 --reruns-delay 1
